### ISSUE TITLE
Won't build on RetroPie Kernel version 5.4.51-v7+

### ISSUE THREAD

**Issue by dnfi** [marqs85/gamecon_gpio_rpi#8]
When compiling it throws the following error -
/var/lib/dkms/gamecon_gpio_rpi/1.4/build/gamecon_gpio_rpi.c:149:5: error: implicit 
declaration of function ‘do_gettimeofday’; did you mean ‘do_settimeofday64’?
[-Werror=implicit-function-declaration]

This appears to be because 'do_gettimeofday' has been deprecated.

**Comment by marqs85** [comment]
Fixed by #7.
